fix: fix fullautocomplete
Zextras/carbonio-contacts-ui pull request #166
Opened 2023-12-19 17:10 UTC by giuliano176

2023-12-21 04:56 UTC, dhavaldodiya submitted a review, later dismissed

2023-12-21 08:03 UTC, beawar requested changes
Considered the history of this FullAutocomplete, probably some additional tests are required.
Imho, when we fix a bug, moreover if directly in release, there should be at least a test for the bug. To be meticulous, there should be enough test to cover all the possible cases for the bug.
Finally, there is no issue ref to see what this fix is about.

2023-12-21 08:24 UTC, giuliano176 commented
> Considered the history of this FullAutocomplete, probably some additional tests are required. Imho, when we fix a bug, moreover if directly in release, there should be at least a test for the bug. To be meticulous, there should be enough test to cover all the possible cases for the bug. Finally, there is no issue ref to see what this fix is about.

- The issue of tests was discussed before this implementation, the common decision taken was that no tests would have been written as the component is problematic and needs to be rewritten, and there are no tests in the module in general. Since the choice widely backfired, we could maybe move this task to lower priority (and leaving groups broken until the next release) so that we will have the time to add all the tests required?

2023-12-21 09:26 UTC, beawar commented
I can help you write tests, we did some in the new branches we are working on, and they all include the usage of the contact input component. We can take those tests as base point and adapt them to test the contact input only.

Can you describe the problem you fixed here, so that we can try to code it?

2023-12-21 09:37 UTC, giuliano176 commented
the issue being solved is the groups being broken because the 'full' attribute being passed as empty string instead of undefined. seen the history of this fix I would rather test also other cases, if you have a set of tests that can be adapted that would help a lot

2023-12-21 10:09 UTC, beawar commented
We can take this one as example test. From this we can build the needed tests. Of course we will need to adapt it to use the contact input directly, but it should not be too hard 

https://github.com/zextras/carbonio-contacts-ui/blob/04bc0a5b73b6cb72b56a778b09eb377638ead3c1/src/v2/views/board/NewContactGroupBoard.test.tsx#L536-L563

2023-12-21 14:37 UTC, beawar commented on src/integrations/tests/contact-input.test.tsx
> +});
we left this useless code, it can be removed

2023-12-21 14:53 UTC, beawar approved these changes
As agreed with @giuliano176 , I consider these tests the base set to cover the fix of this PR. Additional tests will be implemented (and are required from now since there are some examples) each time the contact input will be modified.

2023-12-22 05:03 UTC, dhavaldodiya approved these changes

2023-12-22 05:06 UTC, merged