chore: list item and avatar UI improved
Zextras/carbonio-contacts-ui pull request #2
Opened 2022-01-18 15:14 UTC by geeky-abhishek

Diver Removed from accordion and List Item
Avatar Diameter Changed to 42px and Font Size changed to 14px

2022-01-18 15:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/Zextras/carbonio-contacts-ui?pullRequest=2) <br/>All committers have signed the CLA.

2022-01-19 08:19 UTC, giuliano176 commented on translations/en.json
> +        "edit_email": "Edit Email",
please replace value with "Edit e-mail"

2022-01-19 08:20 UTC, giuliano176 commented on translations/en.json
> +        "edit_invalid_email": "Email is invalid,click to edit it",
please replace Email with E-mail

2022-01-19 12:20 UTC, zovomat requested changes

2022-01-19 12:20 UTC, zovomat commented on translations/en.json
> +        "edit_invalid_email": "E-mail is invalid,click to edit it",
There's a space missing here, after the comma

2022-01-19 12:46 UTC, nubsthead approved these changes, later dismissed

2022-01-20 07:42 UTC, zovomat approved these changes

2022-01-20 08:13 UTC, giuliano176 approved these changes

2022-01-20 08:36 UTC, merged